; STALKER 2 Ultrawide Fix v0.4.0
; Author: Elhait
; GitHub: https://github.com/Elhait/STALKER-2-Ultrawide-Fix-for-UE-5.5.4
; Nexus Mods: https://www.nexusmods.com/stalker2heartofchornobyl/mods/2416
; Configuration changes apply after restarting the game.

[Gameplay]
; Correct gameplay aspect behavior on ultrawide displays.
Enabled=true

[Cinematics]
; Auto, Native, 16:9, 21:9, 32:9
AspectRatio=Auto
